name: empower_ability
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  avatar_glow: ^3.0.1

  camera: ^0.10.5+9
  cloud_firestore: ^4.15.6
  contacts_service: ^0.6.3
  dropdown_button2: ^2.3.9
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.19
  flutter:
    sdk: flutter

  flutter_datetime_picker_plus: ^2.1.0
  flutter_local_notifications: ^14.0.0
  flutter_svg: ^2.0.9
  flutter_tts: ^3.8.5
  fluttertoast: ^8.2.4
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  google_fonts: ^6.1.0
  highlight_text: ^1.7.0
  permission_handler: ^11.3.0
  sizer: ^2.0.15
  speech_to_text: ^6.5.1
  sqflite: ^2.3.2
  telephony: ^0.2.0

  tflite: ^1.1.2
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/icons/
    - lib/medicines/
