// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTHdHHGQ_4_7qQjHPI6WFBvPonF44xU-4',
    appId: '1:112053555715:web:49c175f96a843e5919b436',
    messagingSenderId: '112053555715',
    projectId: 'empower-ability',
    authDomain: 'empower-ability.firebaseapp.com',
    storageBucket: 'empower-ability.appspot.com',
    measurementId: 'G-S0TK7561YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSIOL7FcyAnMdwhRyRP0OhMXgGjGYYT9M',
    appId: '1:112053555715:android:67b315fe0ca439d819b436',
    messagingSenderId: '112053555715',
    projectId: 'empower-ability',
    storageBucket: 'empower-ability.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs44RbqwaRx0DHPqpofZdQQu4hpO1Eob4',
    appId: '1:112053555715:ios:0f627dbd1942f84119b436',
    messagingSenderId: '112053555715',
    projectId: 'empower-ability',
    storageBucket: 'empower-ability.appspot.com',
    iosBundleId: 'com.example.empowerAbility',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs44RbqwaRx0DHPqpofZdQQu4hpO1Eob4',
    appId: '1:112053555715:ios:dec91521bac7697519b436',
    messagingSenderId: '112053555715',
    projectId: 'empower-ability',
    storageBucket: 'empower-ability.appspot.com',
    iosBundleId: 'com.example.empowerAbility.RunnerTests',
  );
}
